export default [
  { id: 1, name: 'Tp. Hà Nội' },
  { id: 2, name: 'Tp. Hồ Chí Minh' },
  { id: 3, name: 'Hà Giang' },
  { id: 4, name: 'Cao Bằng' },
  { id: 5, name: 'Bắc Kạn' },
  { id: 6, name: 'Tuyên Quang' },
  { id: 7, name: 'Lào Cai' },
  { id: 8, name: 'Điện Biên' },
  { id: 9, name: 'Lai Châu' },
  { id: 10, name: 'Sơn La' },
  { id: 11, name: 'Yên Bái' },
  { id: 12, name: 'Hoà Bình' },
  { id: 13, name: 'Thái Nguyên' },
  { id: 14, name: 'Lạng Sơn' },
  { id: 15, name: 'Quảng Ninh' },
  { id: 16, name: 'Bắc Giang' },
  { id: 17, name: 'Phú Thọ' },
  { id: 18, name: 'Vĩnh Phúc' },
  { id: 19, name: 'Bắc Ninh' },
  { id: 20, name: 'Hải Dương' },
  { id: 21, name: 'Hải Phòng' },
  { id: 22, name: 'Hưng Yên' },
  { id: 23, name: 'Thái Bình' },
  { id: 24, name: 'Hà Nam' },
  { id: 25, name: 'Nam Định' },
  { id: 26, name: 'Ninh Bình' },
  { id: 27, name: 'Thanh Hóa' },
  { id: 28, name: 'Nghệ An' },
  { id: 29, name: 'Hà Tĩnh' },
  { id: 30, name: 'Quảng Bình' },
  { id: 31, name: 'Quảng Trị' },
  { id: 32, name: 'Thừa Thiên Huế' },
  { id: 33, name: 'Đà Nẵng' },
  { id: 34, name: 'Quảng Nam' },
  { id: 35, name: 'Quảng Ngãi' },
  { id: 36, name: 'Bình Định' },
  { id: 37, name: 'Phú Yên' },
  { id: 38, name: 'Khánh Hòa' },
  { id: 39, name: 'Ninh Thuận' },
  { id: 40, name: 'Bình Thuận' },
  { id: 41, name: 'Kon Tum' },
  { id: 42, name: 'Gia Lai' },
  { id: 43, name: 'Đắk Lắk' },
  { id: 44, name: 'Đắk Nông' },
  { id: 45, name: 'Lâm Đồng' },
  { id: 46, name: 'Bình Phước' },
  { id: 47, name: 'Tây Ninh' },
  { id: 48, name: 'Bình Dương' },
  { id: 49, name: 'Đồng Nai' },
  { id: 50, name: 'Bà Rịa - Vũng Tàu' },
  { id: 51, name: 'Long An' },
  { id: 52, name: 'Tiền Giang' },
  { id: 53, name: 'Bến Tre' },
  { id: 54, name: 'Trà Vinh' },
  { id: 55, name: 'Vĩnh Long' },
  { id: 56, name: 'Đồng Tháp' },
  { id: 57, name: 'An Giang' },
  { id: 58, name: 'Kiên Giang' },
  { id: 59, name: 'Cần Thơ' },
  { id: 60, name: 'Hậu Giang' },
  { id: 61, name: 'Sóc Trăng' },
  { id: 62, name: 'Bạc Liêu' },
  { id: 63, name: 'Cà Mau' }
]
