version: '3'
services:
  mysql:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysqldata:/var/lib/mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: strapi
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
  str.api:
    container_name: str.api
    image: str.api
    build: .
    ports:
      - "1347:1347"
    volumes:
      - ./uploads:/app/node/public/uploads
  vant:
    container_name: vant
    image: vant
    build: .
    ports:
      - "8002:80"
